name: slug_swole
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
  
    sdk: flutter
  fl_chart: ^0.70.2
  intl: ^0.19.0
  provider: ^6.1.2
  like_button: ^2.0.5
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.3
  firebase_ui_auth: ^1.16.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  firebase_ui_oauth_google: ^1.4.1
  firebase_database: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/fitSlug.png

