// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNZQozkLtd0-Q2fm7mdOtOvxihFHo6H4',
    appId: '1:293709989548:web:5ccf7d8d38e4f155008109',
    messagingSenderId: '293709989548',
    projectId: 'slugswole',
    authDomain: 'slugswole.firebaseapp.com',
    storageBucket: 'slugswole.firebasestorage.app',
    measurementId: 'G-B2QEH246R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTRW9BDKp3gQUzStteblnIwHJIdlbe2rM',
    appId: '1:293709989548:android:35b8727b7ec91b91008109',
    messagingSenderId: '293709989548',
    projectId: 'slugswole',
    storageBucket: 'slugswole.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNH2kirbomgVm3owhBKhkzYJ0_ooWmPsk',
    appId: '1:293709989548:ios:2f437fffc42634a4008109',
    messagingSenderId: '293709989548',
    projectId: 'slugswole',
    storageBucket: 'slugswole.firebasestorage.app',
    iosBundleId: 'com.example.slugSwole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNH2kirbomgVm3owhBKhkzYJ0_ooWmPsk',
    appId: '1:293709989548:ios:2f437fffc42634a4008109',
    messagingSenderId: '293709989548',
    projectId: 'slugswole',
    storageBucket: 'slugswole.firebasestorage.app',
    iosBundleId: 'com.example.slugSwole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJNZQozkLtd0-Q2fm7mdOtOvxihFHo6H4',
    appId: '1:293709989548:web:a03f369cd41f7ee8008109',
    messagingSenderId: '293709989548',
    projectId: 'slugswole',
    authDomain: 'slugswole.firebaseapp.com',
    storageBucket: 'slugswole.firebasestorage.app',
    measurementId: 'G-2L24SZ4MWJ',
  );
}
