// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8K-wwVpRCKcsYGz-tuAyzDmoTUtL4rEg',
    appId: '1:889375264307:web:2c813212e1227d0a709d46',
    messagingSenderId: '889375264307',
    projectId: 'slugswo-aba55',
    authDomain: 'slugswo-aba55.firebaseapp.com',
    storageBucket: 'slugswo-aba55.firebasestorage.app',
    measurementId: 'G-L5MFDCV6WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCzeRoVVk2YpPfVOZpGdwJ8r1fr0dFWMA',
    appId: '1:889375264307:android:25ac48397f1e80ed709d46',
    messagingSenderId: '889375264307',
    projectId: 'slugswo-aba55',
    storageBucket: 'slugswo-aba55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6qLu00rQ-oEvxcvnq9vEIF5B8kTuZYek',
    appId: '1:889375264307:ios:abbcde874625c55a709d46',
    messagingSenderId: '889375264307',
    projectId: 'slugswo-aba55',
    storageBucket: 'slugswo-aba55.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6qLu00rQ-oEvxcvnq9vEIF5B8kTuZYek',
    appId: '1:889375264307:ios:abbcde874625c55a709d46',
    messagingSenderId: '889375264307',
    projectId: 'slugswo-aba55',
    storageBucket: 'slugswo-aba55.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8K-wwVpRCKcsYGz-tuAyzDmoTUtL4rEg',
    appId: '1:889375264307:web:cc2ac40222226a18709d46',
    messagingSenderId: '889375264307',
    projectId: 'slugswo-aba55',
    authDomain: 'slugswo-aba55.firebaseapp.com',
    storageBucket: 'slugswo-aba55.firebasestorage.app',
    measurementId: 'G-SD1N6ZQ9RP',
  );
}
